language: php

sudo: false

addons:
  apt:
    packages:
      - tidy

before_install:
  - |
    if [[ $LANG == JS ]]; then
      nvm install 6.10
      nvm use 6.10
    fi

install:
  - |
    if [[ $LANG == JS ]]; then
      npm install
      npm install codecov
    fi

env:
  global:
    - DB=MYSQL
    - COMPOSER_ROOT_VERSION=4.0.x-dev
    - COVERAGE=0
    - LANG=PHP
    - CODECOV_TOKEN=4de7cd62-439d-47db-8a7b-6d9aa724b32b
    - SCRUT_TOKEN=d0cb5cb06d4d296fe4d849c2bd5008934cbf8afe5d256ef146df32d935a783a6

matrix:
  include:
    - php: 7.0
      env: DB=SQLITE
    - php: 7.0
      env: DB=PGSQL
    - php: 7.0
      env: COVERAGE=1
    - php: 7.0
      env: LINT=1
    - php: 5.6

    # js stuff
    - php: 7.0
      env:
        - LANG=JS
        - COVERAGE=1
    -php: 7.0
      env:
        - LANG=JS
        - LINT=1


  allow_failures:
    - php: 7.0
      env: DB=SQLITE

before_script:
  - |
    if [[ $LANG == PHP ]]; then
      phpenv rehash
      composer self-update || true
      echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      composer install --prefer-dist
      composer require --prefer-dist --no-update silverstripe/recipe-cms:1.0.x-dev silverstripe-themes/simple:~3.2
      composer update
    fi

  - |
    if [[ $DB == PGSQL ]]; then
      composer require silverstripe/postgresql 2.0.x-dev
    fi

  - |
    if [[ $LANG == PHP ]] && [[ $LINT=1 ]]; then
      pyrus install pear/PHP_CodeSniffer;
    fi

#Execute tests with or without coverage
script:
  # php without coverage and without linting
  - |
    if [[ $LANG == PHP ]] && [[ $COVERAGE == 0 ]] && [[ $LINT == 0 ]]; then
      vendor/bin/phpunit
    fi

  # php with coverage
  - |
    if [[ $LANG == PHP ]] && [[ $COVERAGE == 1 ]]; then
      vendor/bin/phpunit --coverage-clover=coverage.clover
    fi

  - |
    if [[ $LANG == PHP ]] && [[ $LINT == 1 ]]; then
      composer run-script lint
    fi

  # javascript without coverage
  - |
    if [[ $LANG == JS ]] && [[ $COVERAGE == 0 ]] && [[ $LINT == 0 ]]; then
      npm run test;
    fi

  # javascript with coverage
  - |
    if [[ $LANG == JS ]] && [[ $COVERAGE == 1 ]]; then
      npm run test:coverage;
    fi

  - |
    if [[ $LANG == JS ]] && [[ $LINT == 1 ]]; then
      npm run lint
    fi

# Upload code coverage when tests pass
after_success:

  # php with coverage
  - |
    if [[ $LANG == PHP ]] && [[ $COVERAGE == 1 ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      travis_retry bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN && -cF javascript -F php && travis_retry php ocular.phar code-coverage:upload --format=php-clover --access-token=$SCRUT_TOKEN coverage.clover;
    fi

  #javascript with coverage
  - |
    if [[ $LANG == JS ]] && [[ $COVERAGE == 1 ]]; then
      ./node_modules/.bin/codecov -F js
    fi