---
Name: coretoolsconfig
---
ContentObject:
  extensions:
    - Linkable
DataList:
  extensions:
    - CoreToolsDataListDataExtension
GlobalSiteSetting:
  extensions:
    - CompanyConfig
    - UtilityNavigationManager
    - FooterNavigationManager
---
Only:
  moduleexists: 'Addressable'
---
GlobalSiteSetting:
  extensions:
    - Addressable
    - Geocodable