---
Name: coretoolsconfig
---
Dynamic\CoreTools\Model\ContentObject:
  extensions:
    - Dynamic\CoreTools\ORM\Linkable
SilverStripe\ORM\DataList:
  extensions:
    - CoreToolsDataListDataExtension
GlobalSiteSetting:
  extensions:
    - CompanyConfig
    - UtilityNavigationManager
    - FooterNavigationManager
---
Only:
  moduleexists: 'Addressable'
---
GlobalSiteSetting:
  extensions:
    - Addressable
    - Geocodable