---
Name: coretoolsconfig
---
Page:
  extensions:
    - Dynamic\CoreTools\ORM\PromoRelation
Dynamic\CoreTools\Model\ContentObject:
  extensions:
    - Dynamic\CoreTools\ORM\Linkable
SilverStripe\ORM\DataList:
  extensions:
    - Dynamic\CoreTools\ORM\CoreToolsDataListDataExtension
Dynamic\CoreTools\Model\GlobalSiteSetting:
  extensions:
    - Dynamic\CoreTools\ORM\CompanyConfig
    - Dynamic\CoreTools\ORM\UtilityNavigationManager
    - Dynamic\CoreTools\ORM\FooterNavigationManager
    - Dynamic\CoreTools\ORM\TemplateConfig
---
Only:
  moduleexists: 'Addressable'
---
Dynamic\CoreTools\ORM\GlobalSiteSetting:
  extensions:
    - Addressable
    - Geocodable